name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'temurin'

      - name: Run tests
        run: ./mvnw test

      - name: Build JAR
        run: ./mvnw package -DskipTests

      - name: Build Docker image
        run: docker build -f taskboard-api/Dockerfile -t taskboard-app .